server:
  port: 9999
  servlet:
    context-path: /base

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    request-context-attribute: request
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss